version: '3.9'

services:

  postgres:
    build: ./database
    container_name: database
    env_file:
      - .env
    expose:
      - "5432"
    ports:
      - "15432:5432"
    shm_size: "256MB"
    volumes:
      -  ./database/data:/var/lib/postgresql/data

  redis:
    build: ./redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "16379:6379"
    shm_size: "256MB"
    volumes:
      - ./redis/conf:/usr/local/etc/redis
      - ./redis/data:/data
