"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path

from shared.env_util import getenv, initenv, getenv_json, getenv_bool
from shared.ng_static import ng_static_dir

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

initenv(BASE_DIR.parent)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-a3c%j#0=e#f-9^d-nixz#j6mj2z=v!fup$1@voeqi!)r=!gvd('

# SECURITY WARNING: don't run with debug turned on in production!
# Debug settings, https://docs.djangoproject.com/en/4.1/ref/settings/#debug
DEBUG = getenv_bool('DJANGO_DEBUG', False)

# Hosts, CORS, CSP, CSRF settings
ALLOWED_HOSTS = getenv_json('DJANGO_ALLOWED_HOSTS', [])
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS = getenv_json('DJANGO_CSRF_TRUSTED_ORIGINS', [])

# Application definition
# https://docs.djangoproject.com/en/4.1/ref/settings/#wsgi-application
WSGI_APPLICATION = 'backend.wsgi.application'

# Application routes
# https://docs.djangoproject.com/en/4.1/ref/settings/#root-urlconf
ROOT_URLCONF = 'backend.urls'

# Installed apps
# https://docs.djangoproject.com/en/4.1/ref/settings/#installed-apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'corsheaders',  # cf. https://pypi.org/project/django-cors-headers/
    'whitenoise.runserver_nostatic',  # cf. https://pypi.org/project/whitenoise/
    'django.contrib.staticfiles',
    'django_probes',  # cf. https://pypi.org/project/django-probes/
    'rest_framework',  # cf. https://pypi.org/project/djangorestframework/,
    'drf_spectacular',  # cf. https://pypi.org/project/drf-spectacular/
    'drf_spectacular_sidecar',  # cf. https://pypi.org/project/drf-spectacular/
]

# Middleware
# https://docs.djangoproject.com/en/4.1/ref/settings/#middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # cf. https://pypi.org/project/django-cors-headers/
    'whitenoise.middleware.WhiteNoiseMiddleware',  # cf. https://whitenoise.evans.io/en/stable/django.html
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Caches
# https://docs.djangoproject.com/en/4.1/topics/cache/#redis
redis_cache_host = getenv('DJANGO_CACHES_DEFAULT_HOST', 'localhost')
redis_cache_port = getenv('DJANGO_CACHES_DEFAULT_PORT', '16379')
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': f'redis://{redis_cache_host}:{redis_cache_port}',
    }
}
# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': getenv('DJANGO_DATABASES_DEFAULT_NAME'),
        'USER': getenv('DJANGO_DATABASES_DEFAULT_USER'),
        'HOST': getenv('DJANGO_DATABASES_DEFAULT_HOST', 'localhost'),
        'PORT': getenv('DJANGO_DATABASES_DEFAULT_PORT', '15432'),
        'PASSWORD': getenv('DJANGO_DATABASES_DEFAULT_PASSWORD'),
    }
}

# Django Rest Framework
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissions'
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# DRF-Spectacular (OpenAPI schema)
# https://drf-spectacular.readthedocs.io/en/latest/settings.html
SPECTACULAR_SETTINGS = {
    'SWAGGER_UI_DIST': 'SIDECAR',  # shorthand to use the sidecar instead
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
    'SCHEMA_PATH_PREFIX': r'/api/\w+'
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

WHITENOISE_ROOT = ng_static_dir(BASE_DIR)
WHITENOISE_INDEX_FILE = bool(WHITENOISE_ROOT)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [WHITENOISE_ROOT]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
